<?php

namespace Database\Seeders;

use App\Models\Book;
use App\Models\Category;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // Admin user
        User::create([
            'name' => 'Chef Admin',
            'email' => 'admin@gourmet.com',
            'password' => Hash::make('password'),
            'role' => 'admin',
        ]);

        // Regular user
        User::create([
            'name' => 'Gourmand User',
            'email' => 'user@gourmet.com',
            'password' => Hash::make('password'),
            'role' => 'gourmand',
        ]);

        $categories = [
            ['name' => 'Pâtisserie Française', 'description' => 'Recettes de pâtisserie française traditionnelle'],
            ['name' => 'Sans Gluten', 'description' => 'Recettes sans gluten pour tous'],
            ['name' => 'Cuisine du Monde', 'description' => 'Voyages culinaires autour du globe'],
            ['name' => 'Végétarien', 'description' => 'Cuisine végétarienne et végane'],
            ['name' => 'Cuisine Méditerranéenne', 'description' => 'Saveurs du bassin méditerranéen'],
            ['name' => 'Boulangerie Artisanale', 'description' => 'Pains, viennoiseries et techniques artisanales'],
            ['name' => 'Cuisine Marocaine', 'description' => 'Classiques marocains, épices et tables familiales'],
            ['name' => 'Cuisine Asiatique', 'description' => 'Saveurs d’Asie, bouillons, nouilles et wok'],
            ['name' => 'Cuisine Santé', 'description' => 'Recettes équilibrées et nutritives au quotidien'],
            ['name' => 'Desserts Modernes', 'description' => 'Desserts créatifs, dressage et textures contemporaines'],
        ];

        $createdCategories = [];

        foreach ($categories as $cat) {
            $category = Category::create($cat);
            $createdCategories[$category->name] = $category->id;
        }

        $books = [
            [
                'title' => 'Secrets de l\'Éclair Parisien',
                'author' => 'Chef Amandine Laurent',
                'description' => 'Un guide précis pour maîtriser éclairs, religieuses et glaçages brillants.',
                'publication_date' => '2023-02-10',
                'category' => 'Pâtisserie Française',
                'is_new_arrival' => false,
                'borrow_count' => 34,
                'consultation_count' => 88,
                'damaged_quantity' => 1,
                'total_copies' => 6,
            ],
            [
                'title' => 'Tartes et Entremets de Saison',
                'author' => 'Chef Lucie Bernard',
                'description' => 'Des desserts de saison élégants avec fruits, crèmes et finitions modernes.',
                'publication_date' => '2024-03-18',
                'category' => 'Pâtisserie Française',
                'is_new_arrival' => true,
                'borrow_count' => 21,
                'consultation_count' => 57,
                'damaged_quantity' => 0,
                'total_copies' => 5,
            ],
            [
                'title' => 'La Bible du Mille-Feuille',
                'author' => 'Chef Étienne Morel',
                'description' => 'Toutes les bases du feuilletage inversé et des garnitures classiques.',
                'publication_date' => '2022-11-06',
                'category' => 'Pâtisserie Française',
                'is_new_arrival' => false,
                'borrow_count' => 18,
                'consultation_count' => 49,
                'damaged_quantity' => 2,
                'total_copies' => 4,
            ],
            [
                'title' => 'Pains Sans Gluten Maison',
                'author' => 'Nora Selmi',
                'description' => 'Des pains moelleux et croustillants sans gluten pour la table quotidienne.',
                'publication_date' => '2023-01-20',
                'category' => 'Sans Gluten',
                'is_new_arrival' => false,
                'borrow_count' => 26,
                'consultation_count' => 63,
                'damaged_quantity' => 0,
                'total_copies' => 5,
            ],
            [
                'title' => 'Brunch Sans Gluten',
                'author' => 'Claire Benyahia',
                'description' => 'Pancakes, cakes salés et douceurs de brunch sans farine traditionnelle.',
                'publication_date' => '2024-05-09',
                'category' => 'Sans Gluten',
                'is_new_arrival' => true,
                'borrow_count' => 16,
                'consultation_count' => 42,
                'damaged_quantity' => 0,
                'total_copies' => 4,
            ],
            [
                'title' => 'Desserts Gourmands Sans Gluten',
                'author' => 'Héloïse Martin',
                'description' => 'Brownies, tartes et biscuits pensés pour une pâtisserie inclusive.',
                'publication_date' => '2022-09-14',
                'category' => 'Sans Gluten',
                'is_new_arrival' => false,
                'borrow_count' => 22,
                'consultation_count' => 51,
                'damaged_quantity' => 1,
                'total_copies' => 5,
            ],
            [
                'title' => 'Escales Culinaires en Asie',
                'author' => 'Yanis Roche',
                'description' => 'Un voyage gourmand à travers les cuisines de rue et les plats familiaux d’Asie.',
                'publication_date' => '2023-06-11',
                'category' => 'Cuisine du Monde',
                'is_new_arrival' => false,
                'borrow_count' => 31,
                'consultation_count' => 77,
                'damaged_quantity' => 0,
                'total_copies' => 7,
            ],
            [
                'title' => 'Saveurs d\'Amérique Latine',
                'author' => 'Paula Jimenez',
                'description' => 'Empanadas, ceviches et sauces vibrantes venues de toute l’Amérique latine.',
                'publication_date' => '2024-01-27',
                'category' => 'Cuisine du Monde',
                'is_new_arrival' => true,
                'borrow_count' => 19,
                'consultation_count' => 54,
                'damaged_quantity' => 0,
                'total_copies' => 4,
            ],
            [
                'title' => 'Autour des Épices du Monde',
                'author' => 'Chef Malik Idrissi',
                'description' => 'Comprendre, associer et cuisiner les épices dans des recettes internationales.',
                'publication_date' => '2022-07-03',
                'category' => 'Cuisine du Monde',
                'is_new_arrival' => false,
                'borrow_count' => 24,
                'consultation_count' => 68,
                'damaged_quantity' => 1,
                'total_copies' => 6,
            ],
            [
                'title' => 'Légumes Rôtis et Tables Végétariennes',
                'author' => 'Sarah Tazi',
                'description' => 'Une cuisine végétarienne généreuse centrée sur les légumes de saison.',
                'publication_date' => '2023-04-22',
                'category' => 'Végétarien',
                'is_new_arrival' => false,
                'borrow_count' => 29,
                'consultation_count' => 73,
                'damaged_quantity' => 0,
                'total_copies' => 6,
            ],
            [
                'title' => 'Bols Verts du Quotidien',
                'author' => 'Maya Lenoir',
                'description' => 'Des bols complets, équilibrés et colorés pour chaque jour de la semaine.',
                'publication_date' => '2024-02-12',
                'category' => 'Végétarien',
                'is_new_arrival' => true,
                'borrow_count' => 14,
                'consultation_count' => 39,
                'damaged_quantity' => 0,
                'total_copies' => 4,
            ],
            [
                'title' => 'Cuisine Végétale Conviviale',
                'author' => 'Nadia Perrin',
                'description' => 'Des plats végétariens faits pour les grandes tablées et les repas partagés.',
                'publication_date' => '2022-10-30',
                'category' => 'Végétarien',
                'is_new_arrival' => false,
                'borrow_count' => 17,
                'consultation_count' => 45,
                'damaged_quantity' => 1,
                'total_copies' => 5,
            ],
            [
                'title' => 'Cuisine des Rivages Méditerranéens',
                'author' => 'Chef Elias Haddad',
                'description' => 'Huile d’olive, herbes et recettes lumineuses inspirées de la Méditerranée.',
                'publication_date' => '2023-03-08',
                'category' => 'Cuisine Méditerranéenne',
                'is_new_arrival' => false,
                'borrow_count' => 28,
                'consultation_count' => 71,
                'damaged_quantity' => 0,
                'total_copies' => 6,
            ],
            [
                'title' => 'Mezzés à Partager',
                'author' => 'Lina Hariri',
                'description' => 'Petites assiettes, dips et pains maison pour des tables généreuses.',
                'publication_date' => '2024-04-16',
                'category' => 'Cuisine Méditerranéenne',
                'is_new_arrival' => true,
                'borrow_count' => 20,
                'consultation_count' => 52,
                'damaged_quantity' => 0,
                'total_copies' => 5,
            ],
            [
                'title' => 'Poissons et Agrumes',
                'author' => 'Chef Bastien Clerc',
                'description' => 'Des recettes marines fraîches relevées par les agrumes et les herbes.',
                'publication_date' => '2022-08-19',
                'category' => 'Cuisine Méditerranéenne',
                'is_new_arrival' => false,
                'borrow_count' => 15,
                'consultation_count' => 41,
                'damaged_quantity' => 2,
                'total_copies' => 5,
            ],
            [
                'title' => 'Le Pain au Levain Facile',
                'author' => 'Thomas Caron',
                'description' => 'Un ouvrage pratique pour créer, nourrir et cuire son levain maison.',
                'publication_date' => '2023-01-05',
                'category' => 'Boulangerie Artisanale',
                'is_new_arrival' => false,
                'borrow_count' => 33,
                'consultation_count' => 84,
                'damaged_quantity' => 0,
                'total_copies' => 7,
            ],
            [
                'title' => 'Viennoiseries du Matin',
                'author' => 'Chef Pauline Vasseur',
                'description' => 'Croissants, pains au chocolat et brioches pour un atelier boulanger complet.',
                'publication_date' => '2024-06-03',
                'category' => 'Boulangerie Artisanale',
                'is_new_arrival' => true,
                'borrow_count' => 23,
                'consultation_count' => 61,
                'damaged_quantity' => 0,
                'total_copies' => 5,
            ],
            [
                'title' => 'Farines, Graines et Croûtes',
                'author' => 'Noé Lambert',
                'description' => 'Comprendre les farines et composer des pains au caractère affirmé.',
                'publication_date' => '2022-12-01',
                'category' => 'Boulangerie Artisanale',
                'is_new_arrival' => false,
                'borrow_count' => 18,
                'consultation_count' => 47,
                'damaged_quantity' => 1,
                'total_copies' => 4,
            ],
            [
                'title' => 'Les Classiques de la Table Marocaine',
                'author' => 'Chef Salma El Fassi',
                'description' => 'Tajines, salades, rfissa et plats emblématiques de la cuisine marocaine.',
                'publication_date' => '2023-05-12',
                'category' => 'Cuisine Marocaine',
                'is_new_arrival' => false,
                'borrow_count' => 35,
                'consultation_count' => 92,
                'damaged_quantity' => 1,
                'total_copies' => 8,
            ],
            [
                'title' => 'Pastilla, Briouates et Fêtes',
                'author' => 'Meriem Alaoui',
                'description' => 'Recettes de réception marocaines, feuilletées et parfumées.',
                'publication_date' => '2024-02-24',
                'category' => 'Cuisine Marocaine',
                'is_new_arrival' => true,
                'borrow_count' => 17,
                'consultation_count' => 46,
                'damaged_quantity' => 0,
            ],
            [
                'title' => 'Épices du Souk',
                'author' => 'Rachid Benkirane',
                'description' => 'Un livre dédié aux mélanges d’épices, marinades et sauces marocaines.',
                'publication_date' => '2022-06-21',
                'category' => 'Cuisine Marocaine',
                'is_new_arrival' => false,
                'borrow_count' => 27,
                'consultation_count' => 64,
                'damaged_quantity' => 2,
            ],
            [
                'title' => 'Wok et Nouilles Maison',
                'author' => 'Aya Nakamura',
                'description' => 'Cuissons rapides, sauces brillantes et recettes de nouilles très variées.',
                'publication_date' => '2023-07-09',
                'category' => 'Cuisine Asiatique',
                'is_new_arrival' => false,
                'borrow_count' => 30,
                'consultation_count' => 79,
                'damaged_quantity' => 0,
            ],
            [
                'title' => 'Bouillons d\'Asie',
                'author' => 'Kenji Sato',
                'description' => 'Des ramen aux phos, un tour complet des grands bouillons asiatiques.',
                'publication_date' => '2024-03-29',
                'category' => 'Cuisine Asiatique',
                'is_new_arrival' => true,
                'borrow_count' => 22,
                'consultation_count' => 58,
                'damaged_quantity' => 0,
            ],
            [
                'title' => 'Petites Bouchées Vapeur',
                'author' => 'Linh Tran',
                'description' => 'Raviolis, bao et bouchées vapeur pour cuisiner à la maison.',
                'publication_date' => '2022-09-08',
                'category' => 'Cuisine Asiatique',
                'is_new_arrival' => false,
                'borrow_count' => 16,
                'consultation_count' => 43,
                'damaged_quantity' => 1,
            ],
            [
                'title' => 'Assiettes Saines du Quotidien',
                'author' => 'Julie Mercier',
                'description' => 'Menus équilibrés, assiettes colorées et habitudes simples pour bien manger.',
                'publication_date' => '2023-04-01',
                'category' => 'Cuisine Santé',
                'is_new_arrival' => false,
                'borrow_count' => 25,
                'consultation_count' => 66,
                'damaged_quantity' => 0,
            ],
            [
                'title' => 'Batch Cooking Léger',
                'author' => 'Camille Roux',
                'description' => 'Préparer la semaine avec des recettes saines, rapides et savoureuses.',
                'publication_date' => '2024-05-13',
                'category' => 'Cuisine Santé',
                'is_new_arrival' => true,
                'borrow_count' => 18,
                'consultation_count' => 44,
                'damaged_quantity' => 0,
            ],
            [
                'title' => 'Protéines Vertes',
                'author' => 'Imane Haddou',
                'description' => 'Légumineuses, céréales et recettes riches en protéines végétales.',
                'publication_date' => '2022-11-17',
                'category' => 'Cuisine Santé',
                'is_new_arrival' => false,
                'borrow_count' => 13,
                'consultation_count' => 38,
                'damaged_quantity' => 1,
            ],
            [
                'title' => 'Desserts de Restaurant à la Maison',
                'author' => 'Chef Olivier Garnier',
                'description' => 'Textures, sauces et dressages pour réaliser des desserts contemporains.',
                'publication_date' => '2023-08-15',
                'category' => 'Desserts Modernes',
                'is_new_arrival' => false,
                'borrow_count' => 32,
                'consultation_count' => 81,
                'damaged_quantity' => 0,
            ],
            [
                'title' => 'Textures, Mousses et Crémeux',
                'author' => 'Élise Fournier',
                'description' => 'Maîtriser les couches, inserts et textures des desserts actuels.',
                'publication_date' => '2024-01-11',
                'category' => 'Desserts Modernes',
                'is_new_arrival' => true,
                'borrow_count' => 20,
                'consultation_count' => 55,
                'damaged_quantity' => 0,
            ],
            [
                'title' => 'L\'Art du Dressage Sucré',
                'author' => 'Matteo Ricci',
                'description' => 'Une approche visuelle du dessert moderne avec sauces, volumes et contraste.',
                'publication_date' => '2022-10-05',
                'category' => 'Desserts Modernes',
                'is_new_arrival' => false,
                'borrow_count' => 14,
                'consultation_count' => 40,
                'damaged_quantity' => 1,
            ],
        ];

        foreach ($books as $book) {
            Book::create([
                'title' => $book['title'],
                'author' => $book['author'],
                'description' => $book['description'],
                'publication_date' => $book['publication_date'],
                'category_id' => $createdCategories[$book['category']],
                'is_new_arrival' => $book['is_new_arrival'],
                'borrow_count' => $book['borrow_count'],
                'consultation_count' => $book['consultation_count'],
                'damaged_quantity' => $book['damaged_quantity'],
            ]);
        }
    }
}
